----
parameters:
  buildConfiguration: 'Release' 

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}' 
    projects: '**/*.csproj'
    displayName: 'Build the project - ${{ parameters.buildConfiguration }}' 
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.BuildConfiguration }}' 
    zipAfterPublish: true
    displayName: 'Publish the project - ${{ parameters.buildConfiguration }}' 
  